//
//  Generated code. Do not modify.
//  source: message-buffer.proto
//
// @dart = 2.12

// ignore_for_file: annotate_overrides, camel_case_types, comment_references
// ignore_for_file: constant_identifier_names, library_prefixes
// ignore_for_file: non_constant_identifier_names, prefer_final_fields
// ignore_for_file: unnecessary_import, unnecessary_this, unused_import

import 'dart:convert' as $convert;
import 'dart:core' as $core;
import 'dart:typed_data' as $typed_data;

@$core.Deprecated('Use rPCDescriptor instead')
const RPC$json = {
  '1': 'RPC',
  '2': [
    {'1': 'RPC_SYSTEM_SHUTDOWN', '2': 0},
    {'1': 'RPC_SYSTEM_REBOOT', '2': 1},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_LIST', '2': 2},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_SET', '2': 3},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_GET', '2': 4},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_UNSET', '2': 5},
    {'1': 'RPC_SYSTEM_OS_TYPE', '2': 6},
    {'1': 'RPC_SYSTEM_TOTAL_MEMORY', '2': 7},
    {'1': 'RPC_SYSTEM_FREE_MEMORY', '2': 8},
    {'1': 'RPC_SYSTEM_USED_MEMORY', '2': 9},
    {'1': 'RPC_SYSTEM_CPU_INFORMATION', '2': 10},
    {'1': 'RPC_SYSTEM_CPU_CORE_COUNT', '2': 11},
    {'1': 'RPC_SYSTEM_SET_HOSTNAME', '2': 12},
    {'1': 'RPC_SYSTEM_GET_HOSTNAME', '2': 13},
    {'1': 'RPC_SYSTEM_SET_DATE_TIME', '2': 14},
    {'1': 'RPC_SYSTEM_SET_TIMEZONE', '2': 15},
    {'1': 'RPC_SYSTEM_FULL_INFORMATION', '2': 16},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_UPDATE', '2': 17},
    {'1': 'RPC_SYSTEM_ENVIRONMENT_BATCH_SET', '2': 18},
    {'1': 'RPC_JVM_VERSION', '2': 100},
    {'1': 'RPC_JVM_VENDOR', '2': 101},
    {'1': 'RPC_JVM_TOTAL_HEAP_SIZE', '2': 102},
    {'1': 'RPC_JVM_MAX_HEAP_SIZE', '2': 103},
    {'1': 'RPC_JVM_USED_HEAP_SIZE', '2': 104},
    {'1': 'RPC_JVM_GC', '2': 105},
    {'1': 'RPC_JVM_RESTART', '2': 106},
    {'1': 'RPC_CONFIG_BACKUP_CREATE', '2': 200},
    {'1': 'RPC_CONFIG_BACKUP_RESTORE', '2': 201},
    {'1': 'RPC_CONFIG_BACKUP_DELETE', '2': 202},
    {'1': 'RPC_CONFIG_BACKUP_LIST', '2': 203},
    {'1': 'RPC_CONFIG_PRINT', '2': 204},
    {'1': 'RPC_DATE_TIME_INFORMATION', '2': 300},
    {'1': 'RPC_DATE_TIME_SYNC_HCTOSYS', '2': 301},
    {'1': 'RPC_DATE_TIME_SYNC_SYSTOHC', '2': 302},
    {'1': 'RPC_NTP_SERVER_NAME', '2': 400},
    {'1': 'RPC_NTP_SYNC', '2': 401},
    {'1': 'RPC_NTP_ACTIVATE', '2': 402},
    {'1': 'RPC_NTP_INFORMATION', '2': 403},
    {'1': 'RPC_MODULE_LIST', '2': 500},
    {'1': 'RPC_MODULE_INSTALL', '2': 501},
    {'1': 'RPC_MODULE_REMOVE', '2': 502},
    {'1': 'RPC_MODULE_ENABLE', '2': 503},
    {'1': 'RPC_MODULE_DISABLE', '2': 504},
    {'1': 'RPC_MODULE_DEPENDENCIES', '2': 505},
    {'1': 'RPC_MODULE_START', '2': 506},
    {'1': 'RPC_MODULE_STOP', '2': 507},
    {'1': 'RPC_MODULE_STOP_ALL', '2': 508},
    {'1': 'RPC_MODULE_START_ALL', '2': 509},
    {'1': 'RPC_MODULE_INIT', '2': 510},
    {'1': 'RPC_NETWORK_ETHERNET_INFORMATION', '2': 600},
    {'1': 'RPC_NETWORK_ETHERNET_SET_IP', '2': 601},
    {'1': 'RPC_NETWORK_ETHERNET_UP', '2': 602},
    {'1': 'RPC_NETWORK_ETHERNET_DOWN', '2': 603},
    {'1': 'RPC_NETWORK_ETHERNET_FLUSH', '2': 604},
    {'1': 'RPC_NETWORK_ROUTE_LIST', '2': 605},
    {'1': 'RPC_NETWORK_ROUTE_ADD', '2': 606},
    {'1': 'RPC_NETWORK_ROUTE_DELETE', '2': 607},
    {'1': 'RPC_NETWORK_ROUTE_DEFAULT_GATEWAY', '2': 608},
    {'1': 'RPC_NETWORK_SET_DNS_NAMESERVER', '2': 609},
    {'1': 'RPC_NETWORK_GET_DNS_NAMESERVER', '2': 610},
    {'1': 'RPC_NETWORK_HOSTS_ADD', '2': 611},
    {'1': 'RPC_NETWORK_HOSTS_DELETE', '2': 612},
    {'1': 'RPC_NETWORK_HOSTS_LIST', '2': 613},
    {'1': 'RPC_NETWORK_NETWORK_ADD', '2': 614},
    {'1': 'RPC_NETWORK_NETWORK_DELETE', '2': 615},
    {'1': 'RPC_NETWORK_NETWORK_LIST', '2': 616},
    {'1': 'RPC_FILESYSTEM_LIST', '2': 700},
    {'1': 'RPC_FILESYSTEM_MOUNT', '2': 701},
    {'1': 'RPC_FILESYSTEM_UMOUNT', '2': 702},
    {'1': 'RPC_FILESYSTEM_SWAP_ON', '2': 703},
    {'1': 'RPC_FILESYSTEM_SWAP_OFF', '2': 704},
    {'1': 'RPC_FILESYSTEM_DIRECTORY_TREE', '2': 705},
    {'1': 'RPC_FILESYSTEM_DELETE_FILE', '2': 706},
    {'1': 'RPC_FILESYSTEM_MOVE_FILE', '2': 707},
    {'1': 'RPC_FILESYSTEM_CREATE_ARCHIVE', '2': 708},
    {'1': 'RPC_FILESYSTEM_EXTRACT_ARCHIVE', '2': 709},
    {'1': 'RPC_FILESYSTEM_CREATE_DIRECTORY', '2': 710},
    {'1': 'RPC_USER_LIST', '2': 800},
    {'1': 'RPC_USER_ADD', '2': 801},
    {'1': 'RPC_USER_REMOVE', '2': 802},
    {'1': 'RPC_USER_PASSWD', '2': 803},
    {'1': 'RPC_USER_LOCK', '2': 804},
    {'1': 'RPC_USER_UNLOCK', '2': 805},
    {'1': 'RPC_USER_UPDATE_ROLE', '2': 806},
    {'1': 'RPC_USER_REALM_LIST', '2': 808},
    {'1': 'RPC_LOG_APPENDER_LIST', '2': 900},
    {'1': 'RPC_LOG_APPENDER_ADD', '2': 901},
    {'1': 'RPC_LOG_APPENDER_REMOVE', '2': 902},
    {'1': 'RPC_LOG_SYSTEM', '2': 903},
    {'1': 'RPC_LOG_KERNEL', '2': 904},
    {'1': 'RPC_SSL_STATUS', '2': 1000},
    {'1': 'RPC_SSL_JKS_UPLOAD', '2': 1001},
    {'1': 'RPC_SSL_JKS_REMOVE', '2': 1002},
    {'1': 'RPC_SSL_JKS_INFO', '2': 1003},
    {'1': 'RPC_CONTAINER_IMAGE_PULL', '2': 2000},
    {'1': 'RPC_CONTAINER_IMAGE_REMOVE', '2': 2001},
    {'1': 'RPC_CONTAINER_IMAGE_LIST', '2': 2002},
    {'1': 'RPC_CONTAINER_IMAGE_SEARCH', '2': 2004},
    {'1': 'RPC_CONTAINER_IMAGE_PRUNE', '2': 2005},
    {'1': 'RPC_CONTAINER_IMAGE_PULL_CANCEL', '2': 2006},
    {'1': 'RPC_CONTAINER_NETWORK_CREATE', '2': 2007},
    {'1': 'RPC_CONTAINER_NETWORK_REMOVE', '2': 2008},
    {'1': 'RPC_CONTAINER_NETWORK_CONNECT', '2': 2009},
    {'1': 'RPC_CONTAINER_NETWORK_DISCONNECT', '2': 2010},
    {'1': 'RPC_CONTAINER_NETWORK_LIST', '2': 2011},
    {'1': 'RPC_CONTAINER_VOLUME_CREATE', '2': 2012},
    {'1': 'RPC_CONTAINER_VOLUME_LIST', '2': 2013},
    {'1': 'RPC_CONTAINER_VOLUME_REMOVE', '2': 2014},
    {'1': 'RPC_CONTAINER_VOLUME_PRUNE', '2': 2015},
    {'1': 'RPC_CONTAINER_POD_CREATE', '2': 2016},
    {'1': 'RPC_CONTAINER_POD_LIST', '2': 2017},
    {'1': 'RPC_CONTAINER_POD_REMOVE', '2': 2018},
    {'1': 'RPC_CONTAINER_POD_PRUNE', '2': 2019},
    {'1': 'RPC_CONTAINER_POD_STATS', '2': 2020},
    {'1': 'RPC_CONTAINER_POD_STOP', '2': 2021},
    {'1': 'RPC_CONTAINER_POD_START', '2': 2022},
    {'1': 'RPC_CONTAINER_POD_KILL', '2': 2023},
    {'1': 'RPC_CONTAINER_POD_KUBE_PLAY', '2': 2024},
    {'1': 'RPC_CONTAINER_POD_KUBE_GENERATE', '2': 2025},
    {'1': 'RPC_CONTAINER_CREATE', '2': 2026},
    {'1': 'RPC_CONTAINER_REMOVE', '2': 2027},
    {'1': 'RPC_CONTAINER_LIST', '2': 2028},
    {'1': 'RPC_CONTAINER_STOP', '2': 2029},
    {'1': 'RPC_CONTAINER_START', '2': 2030},
    {'1': 'RPC_CONTAINER_KILL', '2': 2031},
    {'1': 'RPC_CONTAINER_PRUNE', '2': 2032},
    {'1': 'RPC_CONTAINER_SETTING_REGISTRIES_LOAD', '2': 2033},
    {'1': 'RPC_CONTAINER_SETTING_REGISTRIES_SAVE', '2': 2034},
  ],
};

/// Descriptor for `RPC`. Decode as a `google.protobuf.EnumDescriptorProto`.
final $typed_data.Uint8List rPCDescriptor = $convert.base64Decode(
    'CgNSUEMSFwoTUlBDX1NZU1RFTV9TSFVURE9XThAAEhUKEVJQQ19TWVNURU1fUkVCT09UEAESHw'
    'obUlBDX1NZU1RFTV9FTlZJUk9OTUVOVF9MSVNUEAISHgoaUlBDX1NZU1RFTV9FTlZJUk9OTUVO'
    'VF9TRVQQAxIeChpSUENfU1lTVEVNX0VOVklST05NRU5UX0dFVBAEEiAKHFJQQ19TWVNURU1fRU'
    '5WSVJPTk1FTlRfVU5TRVQQBRIWChJSUENfU1lTVEVNX09TX1RZUEUQBhIbChdSUENfU1lTVEVN'
    'X1RPVEFMX01FTU9SWRAHEhoKFlJQQ19TWVNURU1fRlJFRV9NRU1PUlkQCBIaChZSUENfU1lTVE'
    'VNX1VTRURfTUVNT1JZEAkSHgoaUlBDX1NZU1RFTV9DUFVfSU5GT1JNQVRJT04QChIdChlSUENf'
    'U1lTVEVNX0NQVV9DT1JFX0NPVU5UEAsSGwoXUlBDX1NZU1RFTV9TRVRfSE9TVE5BTUUQDBIbCh'
    'dSUENfU1lTVEVNX0dFVF9IT1NUTkFNRRANEhwKGFJQQ19TWVNURU1fU0VUX0RBVEVfVElNRRAO'
    'EhsKF1JQQ19TWVNURU1fU0VUX1RJTUVaT05FEA8SHwobUlBDX1NZU1RFTV9GVUxMX0lORk9STU'
    'FUSU9OEBASIQodUlBDX1NZU1RFTV9FTlZJUk9OTUVOVF9VUERBVEUQERIkCiBSUENfU1lTVEVN'
    'X0VOVklST05NRU5UX0JBVENIX1NFVBASEhMKD1JQQ19KVk1fVkVSU0lPThBkEhIKDlJQQ19KVk'
    '1fVkVORE9SEGUSGwoXUlBDX0pWTV9UT1RBTF9IRUFQX1NJWkUQZhIZChVSUENfSlZNX01BWF9I'
    'RUFQX1NJWkUQZxIaChZSUENfSlZNX1VTRURfSEVBUF9TSVpFEGgSDgoKUlBDX0pWTV9HQxBpEh'
    'MKD1JQQ19KVk1fUkVTVEFSVBBqEh0KGFJQQ19DT05GSUdfQkFDS1VQX0NSRUFURRDIARIeChlS'
    'UENfQ09ORklHX0JBQ0tVUF9SRVNUT1JFEMkBEh0KGFJQQ19DT05GSUdfQkFDS1VQX0RFTEVURR'
    'DKARIbChZSUENfQ09ORklHX0JBQ0tVUF9MSVNUEMsBEhUKEFJQQ19DT05GSUdfUFJJTlQQzAES'
    'HgoZUlBDX0RBVEVfVElNRV9JTkZPUk1BVElPThCsAhIfChpSUENfREFURV9USU1FX1NZTkNfSE'
    'NUT1NZUxCtAhIfChpSUENfREFURV9USU1FX1NZTkNfU1lTVE9IQxCuAhIYChNSUENfTlRQX1NF'
    'UlZFUl9OQU1FEJADEhEKDFJQQ19OVFBfU1lOQxCRAxIVChBSUENfTlRQX0FDVElWQVRFEJIDEh'
    'gKE1JQQ19OVFBfSU5GT1JNQVRJT04QkwMSFAoPUlBDX01PRFVMRV9MSVNUEPQDEhcKElJQQ19N'
    'T0RVTEVfSU5TVEFMTBD1AxIWChFSUENfTU9EVUxFX1JFTU9WRRD2AxIWChFSUENfTU9EVUxFX0'
    'VOQUJMRRD3AxIXChJSUENfTU9EVUxFX0RJU0FCTEUQ+AMSHAoXUlBDX01PRFVMRV9ERVBFTkRF'
    'TkNJRVMQ+QMSFQoQUlBDX01PRFVMRV9TVEFSVBD6AxIUCg9SUENfTU9EVUxFX1NUT1AQ+wMSGA'
    'oTUlBDX01PRFVMRV9TVE9QX0FMTBD8AxIZChRSUENfTU9EVUxFX1NUQVJUX0FMTBD9AxIUCg9S'
    'UENfTU9EVUxFX0lOSVQQ/gMSJQogUlBDX05FVFdPUktfRVRIRVJORVRfSU5GT1JNQVRJT04Q2A'
    'QSIAobUlBDX05FVFdPUktfRVRIRVJORVRfU0VUX0lQENkEEhwKF1JQQ19ORVRXT1JLX0VUSEVS'
    'TkVUX1VQENoEEh4KGVJQQ19ORVRXT1JLX0VUSEVSTkVUX0RPV04Q2wQSHwoaUlBDX05FVFdPUk'
    'tfRVRIRVJORVRfRkxVU0gQ3AQSGwoWUlBDX05FVFdPUktfUk9VVEVfTElTVBDdBBIaChVSUENf'
    'TkVUV09SS19ST1VURV9BREQQ3gQSHQoYUlBDX05FVFdPUktfUk9VVEVfREVMRVRFEN8EEiYKIV'
    'JQQ19ORVRXT1JLX1JPVVRFX0RFRkFVTFRfR0FURVdBWRDgBBIjCh5SUENfTkVUV09SS19TRVRf'
    'RE5TX05BTUVTRVJWRVIQ4QQSIwoeUlBDX05FVFdPUktfR0VUX0ROU19OQU1FU0VSVkVSEOIEEh'
    'oKFVJQQ19ORVRXT1JLX0hPU1RTX0FERBDjBBIdChhSUENfTkVUV09SS19IT1NUU19ERUxFVEUQ'
    '5AQSGwoWUlBDX05FVFdPUktfSE9TVFNfTElTVBDlBBIcChdSUENfTkVUV09SS19ORVRXT1JLX0'
    'FERBDmBBIfChpSUENfTkVUV09SS19ORVRXT1JLX0RFTEVURRDnBBIdChhSUENfTkVUV09SS19O'
    'RVRXT1JLX0xJU1QQ6AQSGAoTUlBDX0ZJTEVTWVNURU1fTElTVBC8BRIZChRSUENfRklMRVNZU1'
    'RFTV9NT1VOVBC9BRIaChVSUENfRklMRVNZU1RFTV9VTU9VTlQQvgUSGwoWUlBDX0ZJTEVTWVNU'
    'RU1fU1dBUF9PThC/BRIcChdSUENfRklMRVNZU1RFTV9TV0FQX09GRhDABRIiCh1SUENfRklMRV'
    'NZU1RFTV9ESVJFQ1RPUllfVFJFRRDBBRIfChpSUENfRklMRVNZU1RFTV9ERUxFVEVfRklMRRDC'
    'BRIdChhSUENfRklMRVNZU1RFTV9NT1ZFX0ZJTEUQwwUSIgodUlBDX0ZJTEVTWVNURU1fQ1JFQV'
    'RFX0FSQ0hJVkUQxAUSIwoeUlBDX0ZJTEVTWVNURU1fRVhUUkFDVF9BUkNISVZFEMUFEiQKH1JQ'
    'Q19GSUxFU1lTVEVNX0NSRUFURV9ESVJFQ1RPUlkQxgUSEgoNUlBDX1VTRVJfTElTVBCgBhIRCg'
    'xSUENfVVNFUl9BREQQoQYSFAoPUlBDX1VTRVJfUkVNT1ZFEKIGEhQKD1JQQ19VU0VSX1BBU1NX'
    'RBCjBhISCg1SUENfVVNFUl9MT0NLEKQGEhQKD1JQQ19VU0VSX1VOTE9DSxClBhIZChRSUENfVV'
    'NFUl9VUERBVEVfUk9MRRCmBhIYChNSUENfVVNFUl9SRUFMTV9MSVNUEKgGEhoKFVJQQ19MT0df'
    'QVBQRU5ERVJfTElTVBCEBxIZChRSUENfTE9HX0FQUEVOREVSX0FERBCFBxIcChdSUENfTE9HX0'
    'FQUEVOREVSX1JFTU9WRRCGBxITCg5SUENfTE9HX1NZU1RFTRCHBxITCg5SUENfTE9HX0tFUk5F'
    'TBCIBxITCg5SUENfU1NMX1NUQVRVUxDoBxIXChJSUENfU1NMX0pLU19VUExPQUQQ6QcSFwoSUl'
    'BDX1NTTF9KS1NfUkVNT1ZFEOoHEhUKEFJQQ19TU0xfSktTX0lORk8Q6wcSHQoYUlBDX0NPTlRB'
    'SU5FUl9JTUFHRV9QVUxMENAPEh8KGlJQQ19DT05UQUlORVJfSU1BR0VfUkVNT1ZFENEPEh0KGF'
    'JQQ19DT05UQUlORVJfSU1BR0VfTElTVBDSDxIfChpSUENfQ09OVEFJTkVSX0lNQUdFX1NFQVJD'
    'SBDUDxIeChlSUENfQ09OVEFJTkVSX0lNQUdFX1BSVU5FENUPEiQKH1JQQ19DT05UQUlORVJfSU'
    '1BR0VfUFVMTF9DQU5DRUwQ1g8SIQocUlBDX0NPTlRBSU5FUl9ORVRXT1JLX0NSRUFURRDXDxIh'
    'ChxSUENfQ09OVEFJTkVSX05FVFdPUktfUkVNT1ZFENgPEiIKHVJQQ19DT05UQUlORVJfTkVUV0'
    '9SS19DT05ORUNUENkPEiUKIFJQQ19DT05UQUlORVJfTkVUV09SS19ESVNDT05ORUNUENoPEh8K'
    'GlJQQ19DT05UQUlORVJfTkVUV09SS19MSVNUENsPEiAKG1JQQ19DT05UQUlORVJfVk9MVU1FX0'
    'NSRUFURRDcDxIeChlSUENfQ09OVEFJTkVSX1ZPTFVNRV9MSVNUEN0PEiAKG1JQQ19DT05UQUlO'
    'RVJfVk9MVU1FX1JFTU9WRRDeDxIfChpSUENfQ09OVEFJTkVSX1ZPTFVNRV9QUlVORRDfDxIdCh'
    'hSUENfQ09OVEFJTkVSX1BPRF9DUkVBVEUQ4A8SGwoWUlBDX0NPTlRBSU5FUl9QT0RfTElTVBDh'
    'DxIdChhSUENfQ09OVEFJTkVSX1BPRF9SRU1PVkUQ4g8SHAoXUlBDX0NPTlRBSU5FUl9QT0RfUF'
    'JVTkUQ4w8SHAoXUlBDX0NPTlRBSU5FUl9QT0RfU1RBVFMQ5A8SGwoWUlBDX0NPTlRBSU5FUl9Q'
    'T0RfU1RPUBDlDxIcChdSUENfQ09OVEFJTkVSX1BPRF9TVEFSVBDmDxIbChZSUENfQ09OVEFJTk'
    'VSX1BPRF9LSUxMEOcPEiAKG1JQQ19DT05UQUlORVJfUE9EX0tVQkVfUExBWRDoDxIkCh9SUENf'
    'Q09OVEFJTkVSX1BPRF9LVUJFX0dFTkVSQVRFEOkPEhkKFFJQQ19DT05UQUlORVJfQ1JFQVRFEO'
    'oPEhkKFFJQQ19DT05UQUlORVJfUkVNT1ZFEOsPEhcKElJQQ19DT05UQUlORVJfTElTVBDsDxIX'
    'ChJSUENfQ09OVEFJTkVSX1NUT1AQ7Q8SGAoTUlBDX0NPTlRBSU5FUl9TVEFSVBDuDxIXChJSUE'
    'NfQ09OVEFJTkVSX0tJTEwQ7w8SGAoTUlBDX0NPTlRBSU5FUl9QUlVORRDwDxIqCiVSUENfQ09O'
    'VEFJTkVSX1NFVFRJTkdfUkVHSVNUUklFU19MT0FEEPEPEioKJVJQQ19DT05UQUlORVJfU0VUVE'
    'lOR19SRUdJU1RSSUVTX1NBVkUQ8g8=');

@$core.Deprecated('Use realmDescriptor instead')
const Realm$json = {
  '1': 'Realm',
  '2': [
    {'1': 'REALM_NONE', '2': 0},
    {'1': 'REALM_SYSTEM', '2': 1},
    {'1': 'REALM_JVM', '2': 2},
    {'1': 'REALM_NTP_CLIENT', '2': 4},
    {'1': 'REALM_DATE_TIME', '2': 8},
    {'1': 'REALM_CONFIGURATION', '2': 16},
    {'1': 'REALM_ENVIRONMENT', '2': 32},
    {'1': 'REALM_MODULE', '2': 64},
    {'1': 'REALM_NETWORK', '2': 128},
    {'1': 'REALM_USER', '2': 256},
    {'1': 'REALM_LOG', '2': 512},
    {'1': 'REALM_FILESYSTEM', '2': 1024},
    {'1': 'REALM_SSL', '2': 2048},
    {'1': 'REALM_CONTAINER_ENGINE', '2': 4096},
  ],
};

/// Descriptor for `Realm`. Decode as a `google.protobuf.EnumDescriptorProto`.
final $typed_data.Uint8List realmDescriptor = $convert.base64Decode(
    'CgVSZWFsbRIOCgpSRUFMTV9OT05FEAASEAoMUkVBTE1fU1lTVEVNEAESDQoJUkVBTE1fSlZNEA'
    'ISFAoQUkVBTE1fTlRQX0NMSUVOVBAEEhMKD1JFQUxNX0RBVEVfVElNRRAIEhcKE1JFQUxNX0NP'
    'TkZJR1VSQVRJT04QEBIVChFSRUFMTV9FTlZJUk9OTUVOVBAgEhAKDFJFQUxNX01PRFVMRRBAEh'
    'IKDVJFQUxNX05FVFdPUksQgAESDwoKUkVBTE1fVVNFUhCAAhIOCglSRUFMTV9MT0cQgAQSFQoQ'
    'UkVBTE1fRklMRVNZU1RFTRCACBIOCglSRUFMTV9TU0wQgBASGwoWUkVBTE1fQ09OVEFJTkVSX0'
    'VOR0lORRCAIA==');

@$core.Deprecated('Use uploadTypeDescriptor instead')
const UploadType$json = {
  '1': 'UploadType',
  '2': [
    {'1': 'UPLOAD_TYPE_MODULE', '2': 0},
    {'1': 'UPLOAD_TYPE_CONFIG', '2': 1},
    {'1': 'UPLOAD_TYPE_SSL', '2': 2},
    {'1': 'UPLOAD_TYPE_FILE', '2': 3},
  ],
};

/// Descriptor for `UploadType`. Decode as a `google.protobuf.EnumDescriptorProto`.
final $typed_data.Uint8List uploadTypeDescriptor = $convert.base64Decode(
    'CgpVcGxvYWRUeXBlEhYKElVQTE9BRF9UWVBFX01PRFVMRRAAEhYKElVQTE9BRF9UWVBFX0NPTk'
    'ZJRxABEhMKD1VQTE9BRF9UWVBFX1NTTBACEhQKEFVQTE9BRF9UWVBFX0ZJTEUQAw==');

@$core.Deprecated('Use packetDescriptor instead')
const Packet$json = {
  '1': 'Packet',
  '2': [
    {'1': 'iv', '3': 1, '4': 1, '5': 12, '10': 'iv'},
    {'1': 'hash', '3': 2, '4': 1, '5': 12, '10': 'hash'},
    {'1': 'payload', '3': 3, '4': 1, '5': 12, '10': 'payload'},
  ],
};

/// Descriptor for `Packet`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List packetDescriptor = $convert.base64Decode(
    'CgZQYWNrZXQSDgoCaXYYASABKAxSAml2EhIKBGhhc2gYAiABKAxSBGhhc2gSGAoHcGF5bG9hZB'
    'gDIAEoDFIHcGF5bG9hZA==');

@$core.Deprecated('Use payloadDescriptor instead')
const Payload$json = {
  '1': 'Payload',
  '2': [
    {'1': 'metadata', '3': 1, '4': 1, '5': 11, '6': '.jos.Metadata', '10': 'metadata'},
    {'1': 'content', '3': 2, '4': 1, '5': 9, '10': 'content'},
  ],
};

/// Descriptor for `Payload`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List payloadDescriptor = $convert.base64Decode(
    'CgdQYXlsb2FkEikKCG1ldGFkYXRhGAEgASgLMg0uam9zLk1ldGFkYXRhUghtZXRhZGF0YRIYCg'
    'djb250ZW50GAIgASgJUgdjb250ZW50');

@$core.Deprecated('Use metadataDescriptor instead')
const Metadata$json = {
  '1': 'Metadata',
  '2': [
    {'1': 'success', '3': 1, '4': 1, '5': 8, '10': 'success'},
    {'1': 'rpc', '3': 2, '4': 1, '5': 5, '10': 'rpc'},
    {'1': 'error', '3': 3, '4': 1, '5': 5, '10': 'error'},
    {'1': 'need_restart', '3': 4, '4': 1, '5': 8, '10': 'needRestart'},
    {'1': 'message', '3': 7, '4': 1, '5': 9, '10': 'message'},
  ],
};

/// Descriptor for `Metadata`. Decode as a `google.protobuf.DescriptorProto`.
final $typed_data.Uint8List metadataDescriptor = $convert.base64Decode(
    'CghNZXRhZGF0YRIYCgdzdWNjZXNzGAEgASgIUgdzdWNjZXNzEhAKA3JwYxgCIAEoBVIDcnBjEh'
    'QKBWVycm9yGAMgASgFUgVlcnJvchIhCgxuZWVkX3Jlc3RhcnQYBCABKAhSC25lZWRSZXN0YXJ0'
    'EhgKB21lc3NhZ2UYByABKAlSB21lc3NhZ2U=');

